#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update -y
sudo apt-get -y install nginx
sudo chown -R ubuntu /var/www
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
