#!/usr/bin/env bash
# Script that configures an Nginx server to a custom 404 Page
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/h404.html
sudo sed -i "s/server_name _;/server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 \/h404.html;\n\n/" /etc/nginx/sites-available/default
sudo service nginx restart
