#!/usr/bin/env bash
#add header X-Served-By
apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/h404.html
sed -i "s/server_name _;/server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 \/h404.html;\n\n/" /etc/nginx/sites-available/default
sed -i "/server_name _;/a\\\n\tadd_header  X-Served-By  $(hostname);\n\n" /etc/nginx/sites-available/default
service nginx restart
