#!/usr/bin/env bash
# Install HAproxy and config load balancer
CONFIG="
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back
backend http_back
   balance roundrobin
   server 3333-web-01 34.148.195.38 check
   server 3333-web-02 34.229.151.106 check
   "
add-apt-repository -y ppa:vbernat/haproxy-1.7
apt -y update
apt install -y haproxy
echo "$CONFIG" >> /etc/haproxy/haproxy.cfg
service haproxy restart
