#!/usr/bin/env bash
# Install HAproxy and config load balancer
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
sudo apt-get -y update
sudo apt-get -y install haproxy
FIRST_PATH="errorfile 504"
FIRST_PATH_TWO="frontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back\nbackend http_back\n\tbalance roundrobin\n\tserver web-01 34.148.195.38 check\n\tserver web-02 34.229.151.106 check"
SECOND_PATH="/etc/haproxy/haproxy.cfg"
sudo sed -i "/$FIRST_PATH/a$FIRST_PATH_TWO" $SECOND_PATH
sudo service haproxy restart
