#!/usr/bin/env bash
# This script is displaying numbers from 1 to 100: Displays FizzBuzz when the number is a multiple of 3 and 5, Displays Fizz when the number is multiple of 3, Displays Buzz when the number is a multiple of 5
x=1
while [ $x -le 100 ]
do
    if [ $(( x % 3 )) -eq 0 ] && [ $(( x % 5 )) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $(( x % 3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $(( x % 5 )) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$x"
    fi
    x=$(( x + 1 ))
done
