#!/usr/bin/env bash
# This script is displaying The content of the current directory in a list format, only showing the part of the name after the first dash is displayed 
LIST="$(ls)"
for i in $LIST;
do
    echo "$i" | cut -d "-" -f2
done
